name: Docker Image CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'        # Matches tags like 1.2.3, 10.4.0, etc.
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+' # Matches tags like 1.2.3-rc1, 1.2.3-rc12, etc.

jobs:

  build_and_publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_IMAGE_NAME: collector
      IMAGE_TAG: ${{ github.ref_name }} # Use the Git tag as the image tag

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag the multi-platform Docker image for GHCR
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} --push
